// proto/plugin.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/plugin.proto

package generated

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPromptComponentsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SpecTomlContent string                 `protobuf:"bytes,1,opt,name=spec_toml_content,json=specTomlContent,proto3" json:"spec_toml_content,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetPromptComponentsRequest) Reset() {
	*x = GetPromptComponentsRequest{}
	mi := &file_proto_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPromptComponentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPromptComponentsRequest) ProtoMessage() {}

func (x *GetPromptComponentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPromptComponentsRequest.ProtoReflect.Descriptor instead.
func (*GetPromptComponentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *GetPromptComponentsRequest) GetSpecTomlContent() string {
	if x != nil {
		return x.SpecTomlContent
	}
	return ""
}

type GetPromptComponentsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A map to hold all prompt files, keyed by their filename.
	Components map[string]string `protobuf:"bytes,1,rep,name=components,proto3" json:"components,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The user-specific prompt is kept separate as it's generated from the request.
	UserSpecPrompt string `protobuf:"bytes,2,opt,name=user_spec_prompt,json=userSpecPrompt,proto3" json:"user_spec_prompt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetPromptComponentsResponse) Reset() {
	*x = GetPromptComponentsResponse{}
	mi := &file_proto_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPromptComponentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPromptComponentsResponse) ProtoMessage() {}

func (x *GetPromptComponentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPromptComponentsResponse.ProtoReflect.Descriptor instead.
func (*GetPromptComponentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *GetPromptComponentsResponse) GetComponents() map[string]string {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *GetPromptComponentsResponse) GetUserSpecPrompt() string {
	if x != nil {
		return x.UserSpecPrompt
	}
	return ""
}

var File_proto_plugin_proto protoreflect.FileDescriptor

const file_proto_plugin_proto_rawDesc = "" +
	"\n" +
	"\x12proto/plugin.proto\x12\x06plugin\"H\n" +
	"\x1aGetPromptComponentsRequest\x12*\n" +
	"\x11spec_toml_content\x18\x01 \x01(\tR\x0fspecTomlContent\"\xdb\x01\n" +
	"\x1bGetPromptComponentsResponse\x12S\n" +
	"\n" +
	"components\x18\x01 \x03(\v23.plugin.GetPromptComponentsResponse.ComponentsEntryR\n" +
	"components\x12(\n" +
	"\x10user_spec_prompt\x18\x02 \x01(\tR\x0euserSpecPrompt\x1a=\n" +
	"\x0fComponentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012r\n" +
	"\x0eBootCodePlugin\x12`\n" +
	"\x13GetPromptComponents\x12\".plugin.GetPromptComponentsRequest\x1a#.plugin.GetPromptComponentsResponse\"\x00B\x19Z\x17internal/grpc/generatedb\x06proto3"

var (
	file_proto_plugin_proto_rawDescOnce sync.Once
	file_proto_plugin_proto_rawDescData []byte
)

func file_proto_plugin_proto_rawDescGZIP() []byte {
	file_proto_plugin_proto_rawDescOnce.Do(func() {
		file_proto_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_plugin_proto_rawDesc), len(file_proto_plugin_proto_rawDesc)))
	})
	return file_proto_plugin_proto_rawDescData
}

var file_proto_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_plugin_proto_goTypes = []any{
	(*GetPromptComponentsRequest)(nil),  // 0: plugin.GetPromptComponentsRequest
	(*GetPromptComponentsResponse)(nil), // 1: plugin.GetPromptComponentsResponse
	nil,                                 // 2: plugin.GetPromptComponentsResponse.ComponentsEntry
}
var file_proto_plugin_proto_depIdxs = []int32{
	2, // 0: plugin.GetPromptComponentsResponse.components:type_name -> plugin.GetPromptComponentsResponse.ComponentsEntry
	0, // 1: plugin.BootCodePlugin.GetPromptComponents:input_type -> plugin.GetPromptComponentsRequest
	1, // 2: plugin.BootCodePlugin.GetPromptComponents:output_type -> plugin.GetPromptComponentsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_plugin_proto_init() }
func file_proto_plugin_proto_init() {
	if File_proto_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_plugin_proto_rawDesc), len(file_proto_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_plugin_proto_goTypes,
		DependencyIndexes: file_proto_plugin_proto_depIdxs,
		MessageInfos:      file_proto_plugin_proto_msgTypes,
	}.Build()
	File_proto_plugin_proto = out.File
	file_proto_plugin_proto_goTypes = nil
	file_proto_plugin_proto_depIdxs = nil
}
