// proto/plugin.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/plugin.proto

package generated

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BootCodePlugin_GetPromptComponents_FullMethodName = "/plugin.BootCodePlugin/GetPromptComponents"
)

// BootCodePluginClient is the client API for BootCodePlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BootCodePluginClient interface {
	GetPromptComponents(ctx context.Context, in *GetPromptComponentsRequest, opts ...grpc.CallOption) (*GetPromptComponentsResponse, error)
}

type bootCodePluginClient struct {
	cc grpc.ClientConnInterface
}

func NewBootCodePluginClient(cc grpc.ClientConnInterface) BootCodePluginClient {
	return &bootCodePluginClient{cc}
}

func (c *bootCodePluginClient) GetPromptComponents(ctx context.Context, in *GetPromptComponentsRequest, opts ...grpc.CallOption) (*GetPromptComponentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPromptComponentsResponse)
	err := c.cc.Invoke(ctx, BootCodePlugin_GetPromptComponents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BootCodePluginServer is the server API for BootCodePlugin service.
// All implementations must embed UnimplementedBootCodePluginServer
// for forward compatibility.
type BootCodePluginServer interface {
	GetPromptComponents(context.Context, *GetPromptComponentsRequest) (*GetPromptComponentsResponse, error)
	mustEmbedUnimplementedBootCodePluginServer()
}

// UnimplementedBootCodePluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBootCodePluginServer struct{}

func (UnimplementedBootCodePluginServer) GetPromptComponents(context.Context, *GetPromptComponentsRequest) (*GetPromptComponentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPromptComponents not implemented")
}
func (UnimplementedBootCodePluginServer) mustEmbedUnimplementedBootCodePluginServer() {}
func (UnimplementedBootCodePluginServer) testEmbeddedByValue()                        {}

// UnsafeBootCodePluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BootCodePluginServer will
// result in compilation errors.
type UnsafeBootCodePluginServer interface {
	mustEmbedUnimplementedBootCodePluginServer()
}

func RegisterBootCodePluginServer(s grpc.ServiceRegistrar, srv BootCodePluginServer) {
	// If the following call pancis, it indicates UnimplementedBootCodePluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BootCodePlugin_ServiceDesc, srv)
}

func _BootCodePlugin_GetPromptComponents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPromptComponentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BootCodePluginServer).GetPromptComponents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BootCodePlugin_GetPromptComponents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BootCodePluginServer).GetPromptComponents(ctx, req.(*GetPromptComponentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BootCodePlugin_ServiceDesc is the grpc.ServiceDesc for BootCodePlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BootCodePlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.BootCodePlugin",
	HandlerType: (*BootCodePluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPromptComponents",
			Handler:    _BootCodePlugin_GetPromptComponents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/plugin.proto",
}
